spring:
  profiles:
    active: dev   #选dev中的配置
server:
  servlet:
    context-path: /patentSystem
---
server:
  port: 8082
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/patent_system?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.hfut.patentSystem.Dao.Entity
  configuration:
    map-underscore-to-camel-case: true


---
server:
  port: 8083
spring:
  profiles: test

---
server:
  port: 8088
spring:
  profiles: prod